# Generated by Django 4.2.23 on 2025-07-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='recipes/images/')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('cooking_time', models.PositiveIntegerField(help_text='Время приготовления (в минутах)')),
                ('ingredients', models.ManyToManyField(to='ingredients.ingredient')),
                ('tags', models.ManyToManyField(to='tags.tag')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'default_related_name': 'recipes',
            },
        ),
    ]
