# Generated by Django 4.2.23 on 2025-08-05 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'default_related_name': 'recipes', 'ordering': ('-pub_date',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredientamount',
            options={'default_related_name': 'recipe_ingredients', 'ordering': ('recipe', 'ingredient')},
        ),
        migrations.AlterModelOptions(
            name='recipetags',
            options={'default_related_name': 'recipe_tags', 'ordering': ('recipe', 'tag')},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Время приготовления (в минутах)', validators=[django.core.validators.MinValueValidator(1, 'Время приготовления должно быть больше 0'), django.core.validators.MaxValueValidator(32000, 'Время приготовления не может превышать 32 000 минут')], verbose_name='Время приготовления (минуты)'),
        ),
        migrations.AlterField(
            model_name='recipeingredientamount',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0, help_text='Количество ингредиента', validators=[django.core.validators.MinValueValidator(1, 'Количество должно быть больше 0'), django.core.validators.MaxValueValidator(32000, 'Количество не может превышать 32 000')], verbose_name='Количество ингредиента'),
        ),
    ]
